### PR TITLE
Switch to using the black formatter

### PR DESCRIPTION
**Pull request by mpharrigan**
- copy `check/format-incremental` from Cirq (one minor edit to remove an unnecessary exclude line)
- copy `black` version pin from Cirq so our open-source dev environments are mildly in sync.

Instead of formatting everything all at once, I plan on just letting the formatting change slowly over time as PRs format only their changed files. cc @ncrubin @fdmalone @tanujkhattar

### CODE REVIEW

**Comment by fdmalone** [comment]
Why not format everything in one go?

**Comment by fdmalone** [comment]
cirq did this all in one go right, with some git-blame-ignore-revs?

**Comment by tanujkhattar** [comment]
> cirq did this all in one go right, with some git-blame-ignore-revs?


Yes

**Comment by fdmalone** [comment]
With that being said, I'd rather switch to black in one way or another. Can follow up with a bulk reformat.

**Comment by fdmalone** [comment]
xref #835

**Review by fdmalone — APPROVED** [review]

**Pull request merged**
