### PR TITLE
Handle KeyError when using 'old' hdf5 files.

### PR DESCRIPTION
**Pull request by hsim13372**
I ran into a KeyError when I tried to load some 'old' hdf5 files (when attribute 'general_calculations' wasn't yet implemented in MolecularData).

### CODE REVIEW

**Comment by hsim13372** [comment]
I signed it!

**Comment by hsim13372** [comment]
Hi Ryan, 

Thanks a lot for your comment! I just changed the try statement to an if instead. Regarding the testing, I purposefully made this PR without adding to the test because I wanted to ask you and the other developers about what to do when there's an edit similar to this in MolecularData. Would it be okay to add an old or "faulty" data file to the data subdirectory or would this be setting a bad precedent?

**Comment by hsim13372** [comment]
but for now, I'll try to look for a different line in the code that still needs a test and test that.

**Comment by babbush** [comment]
I think you may have fixed the coverage problem just by switching to the "if" statement. The coverage check passed so I went ahead with it. Thanks!

**Pull request merged**
