### PR TITLE
New module to allow easy geometry input by name only.

### PR DESCRIPTION
**Pull request by daochenw**
This is a module that lets the user input only the molecular name, e.g. 'molecular hydrogen' to extract its default geometry from the online PubChem database. This geometry is then parsed into the form acceptable by OpenFermion's MolecularData class. This should hopefully allow non-specialists to more easily get started with OpenFermion, especially given the flexibility of PubChem to also accept colloquial names like 'dry ice' or 'sugar'.

### CODE REVIEW

**Comment by daochenw** [comment]
I signed it!

**Comment by babbush** [comment]
Hi there, and welcome to OpenFermion! Thanks for signing the CLA. Did you sign using your GitHub account name? The CLA bot does not seem to recognize you. In any event, that is a minor issue.

We require that all contributions to OpenFermion come with tests and that the code is covered sufficiently so that overall test coverage in the library is not decreased by more than 0.01%. Please add a test file. You can look at other tests in the library for ideas of how to do this.

Also, please remove the "main" from your code. If you'd like to give an example of your code's functionality the correct place to do that would be by editing one of our ipython notebook demos to demonstrate your functionality.

**Comment by jarrodmcc** [comment]
A few small additional comments before you start your editing are that we use a modular structure to insulate calls to psi4 into our plugins, so this functionality would be better located in the OpenFermion-Psi4 plugin given its dependence on Psi4's geometry routines.  I would also recommend adding more type information on the arguments in the function documentation as well as checking for style guide adherence using pep8 or a similar tool.

**Comment by daochenw** [comment]
Okay, I just signed the CLA with my own GitHub name (before my employer signed), can the bot find it now? Thanks for the suggestions, I'll make the edits.

**Comment by babbush** [comment]
CLA verified. Thank you!

**Comment by daochenw** [comment]
Will make the contribution to Openfermion-Psi4 as Jarrod suggested.

**Pull request closed without merging**
