### PR TITLE
Define __eq__ for SymbolicOperator and eliminate isclose

### PR DESCRIPTION
**Pull request by kevinsung**
This change was discussed at #233 . After this is merged, `op1.isclose(op2)` is no longer valid syntax and `op1 == op2` should be used instead, where `op1` and `op2` are SymbolicOperators such as FermionOperator or QubitOperator.

I did not define `__neq__` yet. I will do that once this and #233 are merged, then use EqualsTester to reformulate some tests for `__eq__` (which will also test `__neq__`).

### CODE REVIEW

**Comment by babbush** [comment]
Is this PR ready for review?

**Comment by kevinsung** [comment]
Yes.

**Comment by babbush** [comment]
I imagine this PR will break plugins like OpenFermion-ProjectQ and OpenFermion-Psi4. This means that we'll either need to bump the version on OpenFermion after this PR, or we'll need to leave __isclose__ in until our next version bump. What do you think?

**Comment by kevinsung** [comment]
I think we should merge this now and bump the version soon. I'm willing to
update the plugins tomorrow (can't today).

**Comment by babbush** [comment]
I think there is also a question about whether we want to implicitly "compress" when doing certain arithmetic operations. For instance, when adding two FermionOperators, should we just delete entries when we find that the absolute values of their coefficients are smaller than the tolerance?

**Comment by babbush** [comment]
Anyways, I looked through the PR and it's great, thanks :+1:

However, I don't want to break the plugins for longer than about an hour. So I want to have the plugin PRs that would fix these changes ready-to-go before I merge. When all that is ready, we will merge, then bump version number. @jarrodmcc does this sound good to you?

@kevinsung are there other breaking changes we should make sure to incorporate before the next version bump?

**Comment by kevinsung** [comment]
Ok that's fine with me, I'll probably get those PR's in tomorrow (or maybe
later today). The compress thing is a separate issue.

Have you looked at #259? It's best to resolve that before the next version.
I'm quite convinced that we should change our Bravyi-Kitaev implementation.

**Comment by kevinsung** [comment]
We should also fix #252 before the next version (that's easy).

**Comment by kevinsung** [comment]
@babbush it turns out that the only plugin that needs to be updated is OpenFermion-ProjectQ. It also turns out that that plugin is broken by the changes made at #257 and #267 . The tests that are broken are named at https://github.com/quantumlib/OpenFermion-ProjectQ/pull/42. I'll probably need some help to fix those.

**Comment by kevinsung** [comment]
Given that OpenFermion-ProjectQ is already broken by the development version of OpenFermion, perhaps we can just merge this as is? It would make it easier to fix the plugins. It's not as if we're breaking the versions people download from pip.

**Comment by babbush** [comment]
Okay

**Pull request merged**
