### PR TITLE
added independent enumeration of horizontal and vertical edges

### LINKED ISSUE #469: In Fermi-Hubbard model, allow specifying different coefficients for horizontal and vertical edges
This is sometimes useful for breaking degeneracies in the spectrum of the tunneling term.

### PR DESCRIPTION
**Pull request by bryano**
Fixes #469

### CODE REVIEW

**Comment by bryano** [comment]
Ready for review.

**Comment by kevinsung** [comment]
Please put "Fixes #469" in the description; that way the issue will be automatically closed.

**Comment by bryano** [comment]
> Please put "Fixes #469" in the description; that way the issue will be automatically closed.

Didn't I do that?

**Comment by bryano** [comment]
Done

**Pull request merged**
