### PR TITLE
made _issmall() a static member of SymbolicOperator addressing #702

### PR DESCRIPTION
**Pull request by cvjjm**
PR implementing the change requested in #702

### CODE REVIEW

**Review by obriente — APPROVED** [review]
LGTM

**Comment by obriente** [comment]
Thanks for sorting that out. I think as soon as you can sort out the CLA issue I can merge.

**Comment by cvjjm** [comment]
I have already asked our legal department to give me permission to sign the CLA.

**Comment by obriente** [comment]
Great, fingers crossed it goes smoothly.

**Comment by cvjjm** [comment]
@googlebot I signed it!

**Comment by cvjjm** [comment]
@googlebot I signed it!

**Comment by cvjjm** [comment]
@googlebot I signed it!

**Comment by cvjjm** [comment]
Also this one is now good to go!

**Comment by obriente** [comment]
Glad this is finally sorted

**Pull request merged**
