### PR TITLE
Fix scipy sqrtm precision issue

### PR DESCRIPTION
**Pull request by fdmalone**
Addresses #815 by replacing la.sqrtm with the square root computed via eigendecomposition. Just bumping the input array's precision to 256 didn't solve the problem.

### CODE REVIEW

**Comment by fdmalone** [comment]
See #865 which tracks the capping of cirq for the CI.

**Comment by fdmalone** [comment]
Will need to cut a new release to fix #851.

**Review by mpharrigan — APPROVED** [review]
thanks fionn

**Comment by fdmalone** [comment]
I need to fix a comment typo don't merge.

**Comment by natestemen** [comment]
Hey happy to see this fixed! Any idea when it will be released? It will help us unblock some dependency upgrades over on [unitaryfund/mitiq](https://github.com/unitaryfund/mitiq).

**Comment by fdmalone** [comment]
@natestemen  I'll aim to release a patch by the end of the week.

**Comment by Misty-W** [comment]
hi @fdmalone, hope you don't mind my asking when the patch mentioned in the previous comment is likely to be released? As my teammate Nate mentioned last week, folks on the Mitiq project are excited to see this upgrade in the pipeline!

**Comment by fdmalone** [comment]
@Misty-W , I just released a patched verison

**Comment by Misty-W** [comment]
> @Misty-W , I just released a patched verison

Fantastic, many thanks @fdmalone!!

**Pull request merged**
