### PR TITLE
Hubbard model periodic fix

### PR DESCRIPTION
**Pull request by kevinsung**
Hi, I am a graduate student at the University of Michigan working with Zhang Jiang from NASA Ames. We indeed find this project useful to us and have been working on some contributions. I submitted a corporate CLA yesterday through the UM Office of Tech Transfer; it was signed by Bryce Pilz (bpilz@umich.edu). My UMich email is kevjsung@umich.edu. The Authorized Contributors Group email address is "um-contributors-to-openfermion@googlegroups.com".

This is just a minor fix to a bug that I found. I added a test that the original code fails, and I fixed the bug.

### CODE REVIEW

**Comment by kevinsung** [comment]
I signed it!

**Comment by babbush** [comment]
Thanks for the contribution Kevin! Yes, if you added the email that is associated with your github account that should be enough. Normally that is enough for the CLA bot to be happy. I can look at the CLAs we have on file in a few hours to try to figure out what is going on in your case. We'll figure it out!

**Comment by babbush** [comment]
Kevin, I think the issue might be with the group CLA. Usually people (even those working for other companies and in academia) sign the individual CLA (which can still cover contributions made on behalf of your employer). Are you able to sign the individual CLA? If so, I think that might fix the problem.

**Comment by kevinsung** [comment]
Ok I just signed an individual agreement.

**Comment by babbush** [comment]
Hmm, from the looks of this Kevin's CLA is good to go but perhaps Ian needs to comment here for things to get approved. Sorry this is so complicated!

**Comment by idk3** [comment]
@googlebot I'm OK with this

**Comment by babbush** [comment]
I overrided CLA bot gone wild by removing branch protections temporarily. Forgive me CLA bot.

**Pull request merged**
