### PR TITLE
format-incremental for _examples_test.py and performance_benchmarks.py

### PR DESCRIPTION
**Pull request by lamberta**
Run `./check/format-incremental --apply` on moved files which failed CI in https://github.com/quantumlib/OpenFermion/pull/614:
- dev_tools/docs/examples/_examples_test.py
- dev_tools/docs/examples/performance_benchmarks.py

Required manually fix that `format-incremental` misformatted.

### CODE REVIEW

**Comment by lamberta** [comment]
Hi ncrubin@, this patch formats the moved files in https://github.com/quantumlib/OpenFermion/pull/614 that failed CI on the `docs` feature branch.

If we update the branch here then I think we can close the revert in https://github.com/quantumlib/OpenFermion/pull/615. But, for CI purposes, if you prefer to push the revert first, then I can update this PR with cherry-picks from the original https://github.com/quantumlib/OpenFermion/pull/614

Thanks! Sorry for the breakage

**Comment by ncrubin** [comment]
@lamberta We need to revert the other PR since it looks like a large number of files were changes along with tests and type checks.  This needs to go through a formal review.  I thought you were updating just documentation?  It looks like you changed logic and removed tests?

**Comment by lamberta** [comment]
> I thought you were updating just documentation?

Yes, that's right. But we need to clear out the `/docs` folder for site documentation, not scripts. These have been moved into `dev_tools/docs/` to match the other projects. Sphinx will no longer be used needs to be factored out eventually, but that's beyond the scope here.

>  It looks like you changed logic and removed tests?

No.  But by moving the `_examples_test.py` and `performance_benchmarks.py` files it triggered the CI, and those files failed the formatting test---it seems those files haven't been checked in a while. No logic or tests have been removed, just applied `./check/format-incremental --apply` and manually tweaked since that script doesn't fix everything needed for the test.

> This needs to go through a formal review

That is fine. Do you want to review updates to the feature branch or when it eventually moves to master?

**Comment by ncrubin** [comment]
Why does (https://github.com/quantumlib/OpenFermion/pull/614) show 25 changed files?

**Comment by ncrubin** [comment]
Also from #614 (docs/_book.yaml) doesn't even show up in the existing code base?

**Comment by lamberta** [comment]
I think that's picking up the latest updates from `master` as well--in an effort to keep the `docs` feature branch up-to-date for a future merge. On that pull request you can see there are commits to master that I'm pulling in to the `docs` branch: https://github.com/quantumlib/OpenFermion/pull/614/commits

But happy to adjust my workflow if you have suggestions. I'm used to using a rebase workflow to keep branches in sync so still figuring out a workflow for the squash-and-merge your repo uses. Suggestions welcome.

**Comment by lamberta** [comment]
> Also from #614 (docs/_book.yaml) doesn't even show up in the existing code base?

Not sure I follow, it's here on the 'docs' branch I"m working on: https://github.com/quantumlib/OpenFermion/tree/docs/docs

**Comment by ncrubin** [comment]
Oh I see this is being merged to a docs branch and not master.  Why is it going onto the docs branch?  And why are we phasing on sphinx?

**Comment by lamberta** [comment]
Ah, seems a communication breakdown with the wider team. Added you to b/159747117 and b/158508086
Happy to chat if you have questions. cc: @dstrain115

**Comment by lamberta** [comment]
Discussed and resolved

**Pull request closed without merging**
