### PR TITLE
Re-arrange import orders.

### PR DESCRIPTION
**Pull request by vtomole**

### CODE REVIEW

**Comment by vtomole** [comment]
The failing lines were not there on my local machine.

**Comment by vtomole** [comment]
Why 

`coverage/coveralls Expected — Waiting for status to be reported`? Thought we removed it.

**Comment by kevinsung** [comment]
I removed the coveralls check.

**Comment by vtomole** [comment]
@kevinsung Please merge.

**Comment by kevinsung** [comment]
@vtomole I think I gave you the access needed to merge yourself.

**Pull request merged**
