### PR TITLE
Fix bug of optional args for get_lowest_n() in Davidson algo

### PR DESCRIPTION
**Pull request by sheilaliuxl**
As suggested by @kevinsung in #361.

1. Fix minor bug;
2. Add unit test for the new benchmark function with (Parallel)LinearQubitOperator;
3. Replace print with logging, so that one can control what to see with DEBUG, INFO, FATAL options;
4. Fix most pylint errors.

### CODE REVIEW

**Comment by sheilaliuxl** [comment]
Seems coverage test is stuck again. @babbush

**Comment by babbush** [comment]
Go for it

**Comment by kevinsung** [comment]
I don't think my account has the permissions.

**Comment by jarrodmcc** [comment]
According to travis, CI builds are now taking on the order of 35-40 minutes each, which is perhaps something we should consider looking into, as it makes even merging new branches into these for additional tests a bit awkward.

**Comment by jarrodmcc** [comment]
Well, the versions are often done in parallel, so 10 minutes wall clock, but sometimes they don't seem to have available computers to do that, so it inches up in time considerably at random

**Pull request merged**
