### PR TITLE
Improve install instructions

### LINKED ISSUE #40: Make distinction between "development" install and "as a lib" install more visually clear
In the readme, I'd do something like this

### Developer installation

blah blah

### User installation (i.e. as a lib)

blah blah

### PR DESCRIPTION
**Pull request by DanielSank**
Fixes #40

### CODE REVIEW

**Comment by babbush** [comment]
Hmm, is your @google email associated with your GitHub account? Usually this only comes up for external contributors.

**Comment by DanielSank** [comment]
@babbush I use my @gmail email for github.

**Comment by babbush** [comment]
That is okay, see what I sent you in gchat. There is an alternative way for Googlers to be recognized by the Google CLA bot.

**Comment by DanielSank** [comment]
@babbush you can use the `view` button to get [here](https://github.com/DanielSank/OpenFermion/blob/66e793168cfb5dc80d079e324a636b98a8dd2bb0/README.rst).

**Pull request merged**
