### PR TITLE
Verstraete cirac

### PR DESCRIPTION
**Pull request by kevinsung**
Partially addresses #100. I think we should leave the issue open if this PR is merged as is.
My implementation works for 2-d square grids with an even number of columns.
Some further work that I leave for the future:
- I only made the transformation work for an even number of columns, but it can straightforwardly be extended to an odd number, as explained in the paper
- It would be great if we could check that the ground state decomposes as a tensor product, but I don't know how to do this. I don't think it works to check that the qubit state vector is a tensor product, since the tensor product structure of the Hilbert space of qubits is different from that of the Hilbert space of fermionic modes.
- The general idea of the transform is to multiply some operators by stabilizer operators to to cancel out Jordan-Wigner strings. Right now, I only handle quadratic operators corresponding to vertical edges, as described in the paper. I haven't thought about whether it's necessary to handle other operators, and how we would do so.
- My implementation works only for spinless models. I think the way to handle spin varies depending on the particular interactions between orbitals of different spin which are present in the Hamiltonian we want to transform, so this might be a little complicated.
- It would be cool to generalize to different 2-d lattice geometries and also higher dimensions.
- I use one particular graph for the auxiliary Hamiltonian, corresponding to Fig. 2a in the paper, but other auxiliary graphs are possible, and we may want to explore them.

### CODE REVIEW

**Comment by babbush** [comment]
Nope, it's not that. Kevin, the time you made the duplicate PR, did you completely 100% delete your fork and then refork?

**Comment by kevinsung** [comment]
Yes, I did.

**Comment by babbush** [comment]
So weird. I'm going to try to add to your PR. Let's see if that activates Travis.

**Comment by kevinsung** [comment]
I'll try it one more time.

**Comment by kevinsung** [comment]
OK let's try that first

**Comment by babbush** [comment]
Ok so me also contributing did not work. But now I have another question: when you reforked, how did you save the changes you make in this PR? What I would have suggested is to:
1) Copy all changed files in this PR to your desktop
2) Delete your fork from GitHub
3) Make a clean fork of OpenFermion
4) Checkout a new feature branch
5) Copy changed files in this PR from your desktop to your feature branch
6) Make the PR again.

Did you already try all of this? This is very perplexing to us. Notice also that when Dave made a test PR recently, it incorrectly lists you (not Dave) as the creator of that PR.

**Comment by kevinsung** [comment]
I didn't re-make the local version of my branch. I can try it now.

**Pull request closed without merging**
