### PR TITLE
AQA tutorials

### PR DESCRIPTION
**Pull request by obriente**
@karlunho requested that I put the tutorials from the course I ran at Leiden University into openfermion. Currently these have cirq (and some openfermioncirq) dependencies as well, not entirely sure how to rearrange around this, but we figured it was better to just throw them in a PR and then debate. @babbush @kevinsung , thoughts?

### CODE REVIEW

**Comment by obriente** [comment]
Looks like everything is failing because of the calls to cirq. Suggestions?

**Comment by vtomole** [comment]
@obriente Why not make this pull request against openfermion-cirq?

**Comment by babbush** [comment]
@vtomole I think this is part of the push we discussed at last OpenFermion meeting to get more of the core documentation into OpenFermion as opposed to the plugins. Not sure the best way to accomplish that though.

**Comment by obriente** [comment]
Yeah, what @babbush said --- I'm personally happy either way.

**Comment by vtomole** [comment]
@obriente @babbush  Okay this is what we can do. Add a new requirements file separate from Openfermions' requirements. Like how we do for `contrib` in Cirq: https://github.com/quantumlib/Cirq/blob/master/cirq/contrib/contrib-requirements.txt. We can have a `tutorials-requirements.txt` that contains the cirq and openfermion-cirq dependencies in the `examples` directory and ignore testing this directory on all of our checks. Then we add a new Github workflow that just runs the example directory.

In Cirq we do

`check/pytest --ignore=cirq/contrib` for the tests where we don't want to run contrib.

**Comment by obriente** [comment]
Seems that there's already a requirements.txt file in /examples - should I run with that? Or should this be separate?

**Comment by vtomole** [comment]
@obriente Seems like we don't even use that file currently so i think it's game. We may want to rename it and remove all the other stuff in it.

**Comment by obriente** [comment]
Alright, I'll rename and remove the other stuff; if people complain than we can change back.

**Comment by obriente** [comment]
This has been added; not sure how to update the workflows though

**Comment by vtomole** [comment]
@obriente Add a step to https://github.com/quantumlib/OpenFermion/blob/master/.github/workflows/ci.yml.

**Comment by obriente** [comment]
@xabomon @StefanoPolla - you might want to review as well. I think the current failure is just a matplotlib issue.

**Comment by obriente** [comment]
Closing this as it's not going to get used.

**Pull request closed without merging**
