### PR TITLE
Add r prefix to strings with backlashes

### PR DESCRIPTION
**Pull request by vtomole**

### CODE REVIEW

**Comment by kevinsung** [comment]
Oh hmm I was wrong about the coveralls check, it still shows up ...

**Comment by kevinsung** [comment]
I removed the coveralls check.

**Comment by vtomole** [comment]
@kevinsung I can't merge.

**Comment by kevinsung** [comment]
@vtomole that's weird, I just checked that I added you as a collaborator with "Write" access. Hmm...

**Pull request merged**
