### PR TITLE
Update _unitary_cc.py

### PR DESCRIPTION
**Pull request by ggd87**
Removing reductant spin orbital indices for the UCCSD singlet generator.

### CODE REVIEW

**Comment by ncrubin** [comment]
@ggd87 did you sign the CLA?  We can get this in once that is done.

**Comment by ggd87** [comment]
@googlebot I signed it!

**Comment by ggd87** [comment]
Apologies, I had already signed it. I never replied with "@googlebot I
signed it!". Just replying now.

**Comment by ncrubin** [comment]
@googlebot I signed it!

**Comment by ncrubin** [comment]
@googlebot I fixed it.

**Pull request merged**
