### PR TITLE
Updating init

### PR DESCRIPTION
**Pull request by obriente**
We had some functions that were sitting around without being exposed. I've gone through and either exposed or made every function either private or added it to the init.

### CODE REVIEW

**Comment by ncrubin** [comment]
@obriente ...so much commit history in one commit!

**Comment by obriente** [comment]
Yeah, I don't get what's happened there - seems like there's a long list of previous commits that haven't been merged...

**Comment by vtomole** [comment]
@obriente  Merge upstream/master into this branch.

**Comment by vtomole** [comment]
Looks like that is not working... Hmm. Did you create this branch off of the latest code in master?

**Comment by obriente** [comment]
@ncrubin , can you add consent here?

**Comment by ncrubin** [comment]
@googlebot I consent.

**Comment by obriente** [comment]
Trying to sort out this mess of pull requests has destroyed this branch - I'll start a new one when I can find the time.

**Pull request closed without merging**
