### PR TITLE
Remove redundant double excitation from UCCSD singlet generator

### PR DESCRIPTION
**Pull request by kevinsung**
@jarrodmcc I messed up yesterday and added a redundant double excitation. I momentarily forgot that electrons are indistinguishable!

### CODE REVIEW

**Comment by jarrodmcc** [comment]
This seems okay, but a thought I had earlier this morning was that if you added back in the index over spins that was in the original uccsd_singlet_operator you might be able to cut the length of the code in half and make it a little easier to understand what's going on.  What are your thoughts on that?

**Comment by kevinsung** [comment]
I'm not sure we could make the code shorter because each set of independent double excitations does not depend on a spin and actually involves both spins. I think *not* explicitly iterating over spin makes it more clear that we are taking advantage of the total spin S^2 symmetry, and also has the advantage of corresponding more closely to the counting of the parameters.

**Comment by kevinsung** [comment]
On second thought, I think you are right. Let me look into it further.

**Comment by kevinsung** [comment]
Okay, @jarrodmcc I've made that change!

**Comment by kevinsung** [comment]
Actually we only needed to loop over the indexing functions. The code is shorter; I hope it's clearer too (not completely sure).

**Comment by kevinsung** [comment]
Ok I made the loop to be over the spin to be more clear. I think I'm really done here; let me know if you have other comments.

**Comment by jarrodmcc** [comment]
The code looks good I think, thanks for the changes! I'll approve after the tests pass

**Pull request merged**
