### PR TITLE
Add pylint

### PR DESCRIPTION
**Pull request by vtomole**
I'll incrementally add to ` dev_tools/conf/.pylintrc` as we fix linting issues. Comes after: https://github.com/quantumlib/OpenFermion/pull/559 is merged.

### CODE REVIEW

**Comment by kevinsung** [comment]
Ooh, it looks like merging the formatting PR caused a lot of conflicts. You might want to start fresh with just adding the pylint files.

**Comment by kevinsung** [comment]
Are you going to add it to Travis too?

**Comment by vtomole** [comment]
@kevinsung Oops. Thanks for the remainder!

**Comment by vtomole** [comment]
@kevinsung Please merge.

**Pull request merged**
