### PR TITLE
Add demo for Jordan-Wigner and Bravyi-Kitaev transforms

### PR DESCRIPTION
**Pull request by kevinsung**
Partially addresses #222 . I think it makes sense to have the Jordan-Wigner and Bravyi-Kitaev transforms in their own demo notebook, with the other more exotic transforms in another one. I took a very pedagogical approach which I think will be helpful to people new to the topic. Of course, feedback on the presentation is welcome.

Some content might need to be changed depending on how #259 is resolved.

### CODE REVIEW

**Comment by babbush** [comment]
@kevinsung I guess this needs to be merged after the eq PR?

**Comment by kevinsung** [comment]
Indeed, and preferably after resolving #259 too. I understand #259 might need more input from people though and we don't need to wait.

**Comment by babbush** [comment]
Is this good to go?

**Comment by kevinsung** [comment]
Not yet, I'll make the necessary changes and let you know when.

**Comment by kevinsung** [comment]
Ready once checks pass!

**Comment by kevinsung** [comment]
Wait, I realized this and the binary transforms demo are not being tested, I'll fix that...

**Comment by kevinsung** [comment]
Ok ready.

**Pull request merged**
