### PR TITLE
OpenFermion-Cirq merge: Library code

### PR DESCRIPTION
**Pull request by kevinsung**
As discussed at the weekly OpenFermion sync, we have decided to merge [OpenFermion-Cirq](https://github.com/quantumlib/OpenFermion-Cirq) into OpenFermion. The main benefits are consolidation of functionality and removing the overhead of maintaining two separate libraries.

This pull request moves the library code from OpenFermion-Cirq, except for the `variational` and `optimize` modules, which are deprecated. I plan to move the examples in a separate pull request, but let me know if you'd like them in this one.

### CODE REVIEW

**Comment by ncrubin** [comment]
@kevinsung is there a way to make this draft open so I can submit commits to it?  I thought PR's are open by default but maybe not drafts?  

Anyways, I updated this code to work with the new module structure.  It is now passing tests but is probably lack in coverage.

You can see the modifications on my branch of your draft PR. https://github.com/ncrubin/OpenFermion/tree/kevinsung-ofc-merge

**Comment by kevinsung** [comment]
I marked this draft ready for review; maybe that does it? In any case, I can add your commits myself. I'll also get the test coverage passing.

**Comment by kevinsung** [comment]
@ncrubin it looks like you deleted your branch. Would you mind restoring it so I can add your commits?

**Comment by ncrubin** [comment]
@kevinsung Thank you for doing this!

**Pull request merged**
